export {
  RiCloseLine,
  RiFlagLine,
  RiHome2Line,
  RiHome4Line,
  RiRefreshLine,
  RiMailLine,
  RiShieldCheckFill,
  RiAwardFill,
  RiGitMergeFill,
  RiGift2Fill,
  RiGithubFill,
  RiSunLine,
  RiMoonClearLine,
} from 'oh-vue-icons/icons/ri/index.js'
